package bms;

import java.sql.*;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Umar Aziz
 */
public class AddAccount extends javax.swing.JFrame {

        public String RandNum(){
        Random rand = new Random(System.currentTimeMillis());
        long num = rand.nextInt(9) * 100000 + rand.nextInt(900000) * 10000000000L + rand.nextInt((int) 10000000000L);
        String strNum = String.format("%016d", num);
        return strNum;
        }
        public int Rand3(){

        Random rand = new Random();
        return rand.nextInt(900) + 100;
        }
        /**}
     * Creates new form BankerBoard
     */
    
   
    public AddAccount() {
        initComponents();
        accno.setText(RandNum());
        debitno.setText(RandNum());
        creditno.setText(RandNum());
        creditcvv.setText(Integer.toString(Rand3()));
        debitcvv.setText(Integer.toString(Rand3()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        fnamefield = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        moblabel = new javax.swing.JLabel();
        fname = new javax.swing.JLabel();
        adresslabel = new javax.swing.JLabel();
        acctypelabel = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        mobno = new javax.swing.JTextField();
        balance = new javax.swing.JTextField();
        addresslabel = new javax.swing.JLabel();
        pin = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        pinlabel = new javax.swing.JLabel();
        addbtn = new javax.swing.JButton();
        balancelabel = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        pinlabel1 = new javax.swing.JLabel();
        accno = new javax.swing.JTextField();
        acctypelabel1 = new javax.swing.JLabel();
        creditno = new javax.swing.JTextField();
        acctypelabel2 = new javax.swing.JLabel();
        debitno = new javax.swing.JTextField();
        acctypelabel3 = new javax.swing.JLabel();
        creditcvv = new javax.swing.JTextField();
        acctypelabel4 = new javax.swing.JLabel();
        debitcvv = new javax.swing.JTextField();
        creditnoalert = new javax.swing.JLabel();
        debitnoalert = new javax.swing.JLabel();
        accnoalert = new javax.swing.JLabel();
        debitbtn = new javax.swing.JButton();
        accbtn = new javax.swing.JButton();
        creditbtn = new javax.swing.JButton();
        current = new javax.swing.JRadioButton();
        saving = new javax.swing.JRadioButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        Delete = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        accpic = new javax.swing.JLabel();
        accadd = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        cashpic = new javax.swing.JLabel();
        cashwith = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        logout = new javax.swing.JLabel();
        logoutpic = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        logout1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(21, 103, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(1023, 640));

        fnamefield.setBackground(new java.awt.Color(255, 255, 255));
        fnamefield.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Enter Details for Creating an Account");
        fnamefield.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 1020, -1));

        moblabel.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        moblabel.setText("Mobile Number :");
        fnamefield.add(moblabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 150, 30));

        fname.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        fname.setText("Name :");
        fnamefield.add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 60, 30));

        adresslabel.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        adresslabel.setText("Email Address :");
        fnamefield.add(adresslabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 150, 30));

        acctypelabel.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        acctypelabel.setText("Account Type :");
        fnamefield.add(acctypelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, 130, 30));

        email.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        fnamefield.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 279, 30));

        mobno.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        mobno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobnoActionPerformed(evt);
            }
        });
        fnamefield.add(mobno, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 279, 30));

        balance.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        balance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balanceActionPerformed(evt);
            }
        });
        fnamefield.add(balance, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 470, 279, 30));

        addresslabel.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        addresslabel.setText("Residential Address :");
        fnamefield.add(addresslabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, 30));

        pin.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        pin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinActionPerformed(evt);
            }
        });
        fnamefield.add(pin, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 279, 30));

        address.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressActionPerformed(evt);
            }
        });
        fnamefield.add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 279, 30));

        pinlabel.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        pinlabel.setText(" PIN :");
        fnamefield.add(pinlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 60, 30));

        addbtn.setBackground(new java.awt.Color(21, 103, 153));
        addbtn.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        addbtn.setForeground(new java.awt.Color(255, 255, 255));
        addbtn.setText("Add Account");
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });
        fnamefield.add(addbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 530, 171, 51));

        balancelabel.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        balancelabel.setText("Cash Deposited :");
        fnamefield.add(balancelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 440, 150, 30));

        name.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        fnamefield.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 279, -1));

        pinlabel1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        pinlabel1.setText("Account Number :");
        fnamefield.add(pinlabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 150, 30));

        accno.setEditable(false);
        accno.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        accno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accnoActionPerformed(evt);
            }
        });
        accno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                accnoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                accnoKeyReleased(evt);
            }
        });
        fnamefield.add(accno, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 279, 30));

        acctypelabel1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        acctypelabel1.setText("Credit Card Number :");
        fnamefield.add(acctypelabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, 180, 30));

        creditno.setEditable(false);
        creditno.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        creditno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditnoActionPerformed(evt);
            }
        });
        creditno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                creditnoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                creditnoKeyReleased(evt);
            }
        });
        fnamefield.add(creditno, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, 279, 30));

        acctypelabel2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        acctypelabel2.setText("Debit Card Number :");
        fnamefield.add(acctypelabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 230, 180, 30));

        debitno.setEditable(false);
        debitno.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        debitno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                debitnoActionPerformed(evt);
            }
        });
        debitno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                debitnoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                debitnoKeyReleased(evt);
            }
        });
        fnamefield.add(debitno, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 260, 279, 30));

        acctypelabel3.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        acctypelabel3.setText("Credit Card CVV :");
        fnamefield.add(acctypelabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 300, 180, 30));

        creditcvv.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        creditcvv.setEnabled(false);
        creditcvv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditcvvActionPerformed(evt);
            }
        });
        fnamefield.add(creditcvv, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 330, 279, 30));

        acctypelabel4.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        acctypelabel4.setText("Debit Card CVV :");
        fnamefield.add(acctypelabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 370, 180, 30));

        debitcvv.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        debitcvv.setEnabled(false);
        debitcvv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                debitcvvActionPerformed(evt);
            }
        });
        fnamefield.add(debitcvv, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 400, 279, 30));

        creditnoalert.setForeground(new java.awt.Color(204, 0, 0));
        fnamefield.add(creditnoalert, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 220, 340, -1));

        debitnoalert.setForeground(new java.awt.Color(204, 0, 0));
        fnamefield.add(debitnoalert, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 290, 380, -1));

        accnoalert.setForeground(new java.awt.Color(204, 0, 0));
        fnamefield.add(accnoalert, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, 360, -1));

        debitbtn.setText("Regenerate");
        debitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                debitbtnActionPerformed(evt);
            }
        });
        fnamefield.add(debitbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 260, -1, 30));

        accbtn.setText("Regenerate");
        accbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accbtnActionPerformed(evt);
            }
        });
        fnamefield.add(accbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 470, -1, 30));

        creditbtn.setText("Regenerate");
        creditbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditbtnActionPerformed(evt);
            }
        });
        fnamefield.add(creditbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 190, -1, 30));

        buttonGroup1.add(current);
        current.setText("Current");
        fnamefield.add(current, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 120, -1, -1));

        buttonGroup1.add(saving);
        saving.setText("Saving");
        fnamefield.add(saving, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 120, -1, -1));

        jPanel7.setBackground(new java.awt.Color(21, 103, 153));
        jPanel7.setPreferredSize(new java.awt.Dimension(203, 66));
        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel7MouseExited(evt);
            }
        });

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/icons8-macos-close-30.png"))); // NOI18N

        Delete.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        Delete.setForeground(new java.awt.Color(255, 255, 255));
        Delete.setText("Delete / Reset");
        Delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Delete)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(Delete)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(21, 103, 153));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel2MouseExited(evt);
            }
        });

        accpic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/addprofile.png"))); // NOI18N

        accadd.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        accadd.setForeground(new java.awt.Color(255, 255, 255));
        accadd.setText("Add Account");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(accpic)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(accadd, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(accadd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(accpic, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
        );

        jPanel9.setBackground(new java.awt.Color(21, 103, 153));
        jPanel9.setPreferredSize(new java.awt.Dimension(203, 66));
        jPanel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel9MouseExited(evt);
            }
        });

        cashpic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/icons8-money-bag-rupee-30 (2).png"))); // NOI18N

        cashwith.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        cashwith.setForeground(new java.awt.Color(255, 255, 255));
        cashwith.setText("Cash Deal");
        cashwith.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cashwithMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(cashpic)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cashwith, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cashpic, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(cashwith)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(21, 103, 153));
        jPanel4.setPreferredSize(new java.awt.Dimension(203, 66));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel4MouseExited(evt);
            }
        });

        logout.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setText(" Exit All");

        logoutpic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/logout.png"))); // NOI18N
        logoutpic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutpicMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(logoutpic)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logout, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(logoutpic)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(21, 103, 153));
        jPanel5.setPreferredSize(new java.awt.Dimension(203, 66));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel5MouseExited(evt);
            }
        });

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/icons8-logout-rounded-left-30.png"))); // NOI18N

        logout1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        logout1.setForeground(new java.awt.Color(255, 255, 255));
        logout1.setText("Logout");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(logout1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
            .addComponent(logout1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fnamefield, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(65, 65, 65))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fnamefield, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1095, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 675, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed
           
            try {
            Statement st = SplashScreen.db.conn.createStatement();
            if(current.isSelected())
                { 
                    st.executeUpdate("INSERT INTO information(name, email, mobno, pin, acctype, balance, accno, creditno, debitno, creditcvv, debitcvv, address, username, password, answer) VALUES ('"+name.getText()+"','"+email.getText()+"','"+mobno.getText()+"','"+pin.getText()+"','"+current.getText()+"','"+balance.getText()+"','"+accno.getText()+"','"+creditno.getText()+"','"+debitno.getText()+"','"+creditcvv.getText()+"','"+debitcvv.getText()+"','"+address.getText()+"','"+null+"','"+null+"','"+null+"')");}
            else if(saving.isSelected())
                    {  
                        st.executeUpdate("INSERT INTO information(name, email, mobno, pin, acctype, balance, accno, creditno, debitno, creditcvv, debitcvv, address, username, password, answer) VALUES ('"+name.getText()+"','"+email.getText()+"','"+mobno.getText()+"','"+pin.getText()+"','"+saving.getText()+"','"+balance.getText()+"','"+accno.getText()+"','"+creditno.getText()+"','"+debitno.getText()+"','"+creditcvv.getText()+"','"+debitcvv.getText()+"','"+address.getText()+"','nul','"+null+"','"+null+"')");}
            
            
            Mail.send(email.getText(),"Your Account Created Successfully","<h1>Welcome to DIGITAL BANK</h1> <p>Hi,"+name.getText()+" Thank You for Creating Account.</p><p>Rs."+balance.getText()+" Deposited to Your Account</p>");
            JOptionPane.showMessageDialog(null, "Account Created Successfully");
        } catch (SQLException ex) {
            Logger.getLogger(AddAccount.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_addbtnActionPerformed

    private void addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressActionPerformed

    private void pinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pinActionPerformed

    private void balanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_balanceActionPerformed

    private void mobnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mobnoActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void accnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accnoActionPerformed

    private void creditnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_creditnoActionPerformed

    private void debitnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_debitnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_debitnoActionPerformed

    private void creditcvvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditcvvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_creditcvvActionPerformed

    private void debitcvvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_debitcvvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_debitcvvActionPerformed

    private void creditnoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_creditnoKeyReleased
        boolean check_cn= false;
        Statement st;
        try {
            st = SplashScreen.db.conn.createStatement();
            ResultSet rs=st.executeQuery("SELECT * from information");
            while(rs.next()){
                String cn=rs.getString(8);
                if(cn.equals(creditno.getText())){
                    check_cn=true;
                }
            
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(CreatePassword.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if(check_cn){
            creditnoalert.setText("Credit Card Number already exists! please try another");

        }
    }//GEN-LAST:event_creditnoKeyReleased

    private void creditnoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_creditnoKeyPressed
            creditnoalert.setText(null);
            
    }//GEN-LAST:event_creditnoKeyPressed

    private void debitnoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_debitnoKeyReleased
       boolean check= false;
        Statement st;
        try {
            st = SplashScreen.db.conn.createStatement();
            ResultSet rs=st.executeQuery("SELECT * from information");
            while(rs.next()){
                String dn=rs.getString(9);
                if(dn.equals(debitno.getText())){
                    check=true;
                }
            
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(CreatePassword.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if(check){
            debitnoalert.setText("Debit Card Number already exists! please try another");

        }
    }//GEN-LAST:event_debitnoKeyReleased

    private void debitnoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_debitnoKeyPressed
                debitnoalert.setText(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_debitnoKeyPressed

    private void accnoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_accnoKeyReleased
boolean check= false;
        Statement st;
        try {
            st = SplashScreen.db.conn.createStatement();
            ResultSet rs=st.executeQuery("SELECT * from information");
            while(rs.next()){
                String acc=rs.getString(7);
                if(acc.equals(accno.getText())){
                    check=true;
                }
            
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(CreatePassword.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if(check){
            accnoalert.setText("Account Number already exists! please try another");

        }    }//GEN-LAST:event_accnoKeyReleased

    private void accnoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_accnoKeyPressed
        accnoalert.setText(null);        // TODO add your handling code here:
    }//GEN-LAST:event_accnoKeyPressed

    private void debitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_debitbtnActionPerformed
        debitno.setText(RandNum());        // TODO add your handling code here:
    }//GEN-LAST:event_debitbtnActionPerformed

    private void accbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accbtnActionPerformed
        accno.setText(RandNum());
    }//GEN-LAST:event_accbtnActionPerformed

    private void creditbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditbtnActionPerformed
        creditno.setText(RandNum());
    }//GEN-LAST:event_creditbtnActionPerformed

    private void DeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteMouseClicked
        // TODO add your handling code here:
        DeleteAccount Dl = new DeleteAccount();
        Dl.setVisible(true);
        dispose();
    }//GEN-LAST:event_DeleteMouseClicked

    private void jPanel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseClicked
        DeleteAccount da=new DeleteAccount();
        da.setVisible(true);
        dispose();
    }//GEN-LAST:event_jPanel7MouseClicked

    private void jPanel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseEntered
        jPanel7.setBackground(new java.awt.Color(16, 69, 105));
    }//GEN-LAST:event_jPanel7MouseEntered

    private void jPanel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseExited
        jPanel7.setBackground(new java.awt.Color(21,103,153));// TODO add your handling code here:
    }//GEN-LAST:event_jPanel7MouseExited

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        AddAccount aa=new AddAccount();
        aa.setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2MouseClicked

    private void jPanel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseEntered
        jPanel2.setBackground(new java.awt.Color(16, 69, 105));
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2MouseEntered

    private void jPanel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseExited
        jPanel2.setBackground(new java.awt.Color(21,103,153));// TODO add your handling code here:
    }//GEN-LAST:event_jPanel2MouseExited

    private void cashwithMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cashwithMouseClicked
        // TODO add your handling code here:
        CashDeposit cd=new CashDeposit();
        cd.setVisible(true);
        dispose();
    }//GEN-LAST:event_cashwithMouseClicked

    private void jPanel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseClicked
        CashDeposit cd=new CashDeposit();
        cd.setVisible(true);
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jPanel9MouseClicked

    private void jPanel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseEntered
        jPanel9.setBackground(new java.awt.Color(16, 69, 105));
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel9MouseEntered

    private void jPanel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseExited
        jPanel9.setBackground(new java.awt.Color(21,103,153));// TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel9MouseExited

    private void logoutpicMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutpicMouseClicked

    }//GEN-LAST:event_logoutpicMouseClicked

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jPanel4MouseClicked

    private void jPanel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseEntered
        jPanel4.setBackground(new java.awt.Color(16, 69, 105));
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel4MouseEntered

    private void jPanel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseExited
        jPanel4.setBackground(new java.awt.Color(21,103,153));// TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel4MouseExited

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
        LoginBanker lb=new LoginBanker();
        lb.setVisible(true);
        dispose();
    }//GEN-LAST:event_jPanel5MouseClicked

    private void jPanel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseEntered
        jPanel5.setBackground(new java.awt.Color(16, 69, 105));
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel5MouseEntered

    private void jPanel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseExited
        jPanel5.setBackground(new java.awt.Color(21,103,153));// TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel5MouseExited

    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Delete;
    private javax.swing.JLabel accadd;
    private javax.swing.JButton accbtn;
    private javax.swing.JTextField accno;
    private javax.swing.JLabel accnoalert;
    private javax.swing.JLabel accpic;
    private javax.swing.JLabel acctypelabel;
    private javax.swing.JLabel acctypelabel1;
    private javax.swing.JLabel acctypelabel2;
    private javax.swing.JLabel acctypelabel3;
    private javax.swing.JLabel acctypelabel4;
    private javax.swing.JButton addbtn;
    private javax.swing.JTextField address;
    private javax.swing.JLabel addresslabel;
    private javax.swing.JLabel adresslabel;
    private javax.swing.JTextField balance;
    private javax.swing.JLabel balancelabel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel cashpic;
    private javax.swing.JLabel cashwith;
    private javax.swing.JButton creditbtn;
    private javax.swing.JTextField creditcvv;
    private javax.swing.JTextField creditno;
    private javax.swing.JLabel creditnoalert;
    private javax.swing.JRadioButton current;
    private javax.swing.JButton debitbtn;
    private javax.swing.JTextField debitcvv;
    private javax.swing.JTextField debitno;
    private javax.swing.JLabel debitnoalert;
    private javax.swing.JTextField email;
    private javax.swing.JLabel fname;
    private javax.swing.JPanel fnamefield;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel logout1;
    private javax.swing.JLabel logoutpic;
    private javax.swing.JLabel moblabel;
    private javax.swing.JTextField mobno;
    private javax.swing.JTextField name;
    private javax.swing.JTextField pin;
    private javax.swing.JLabel pinlabel;
    private javax.swing.JLabel pinlabel1;
    private javax.swing.JRadioButton saving;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
