package bms;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Umar Aziz
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundcolor = new javax.swing.JPanel();
        banklogo = new javax.swing.JLabel();
        option = new javax.swing.JLabel();
        title2 = new javax.swing.JLabel();
        title1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Loginbankerpanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Loginbankerpanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        backgroundcolor.setBackground(new java.awt.Color(21, 103, 153));
        backgroundcolor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        banklogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        banklogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/small logo.png"))); // NOI18N
        backgroundcolor.add(banklogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 203, -1));

        option.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        option.setForeground(new java.awt.Color(255, 255, 255));
        option.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        option.setText("Please select an option:");
        backgroundcolor.add(option, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 340, 280, -1));

        title2.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        title2.setForeground(new java.awt.Color(255, 255, 255));
        title2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title2.setText("Digital Bank Management System");
        backgroundcolor.add(title2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 390, 20));

        title1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        title1.setForeground(new java.awt.Color(255, 255, 255));
        title1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title1.setText("Welcome to ");
        backgroundcolor.add(title1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, 220, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/icons8-close-window-30.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        backgroundcolor.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(767, 0, -1, -1));

        Loginbankerpanel.setBackground(new java.awt.Color(21, 103, 153));
        Loginbankerpanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        Loginbankerpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginbankerpanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LoginbankerpanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LoginbankerpanelMouseExited(evt);
            }
        });
        Loginbankerpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Login as User");
        Loginbankerpanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 210, 20));

        backgroundcolor.add(Loginbankerpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 490, 210, 60));

        Loginbankerpanel1.setBackground(new java.awt.Color(21, 103, 153));
        Loginbankerpanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        Loginbankerpanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Loginbankerpanel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Loginbankerpanel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Loginbankerpanel1MouseExited(evt);
            }
        });
        Loginbankerpanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Login as Banker");
        Loginbankerpanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 210, 20));

        backgroundcolor.add(Loginbankerpanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 410, 210, 60));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0,90));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );

        backgroundcolor.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 610));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/mainbankbg.jpg"))); // NOI18N
        backgroundcolor.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 610));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundcolor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundcolor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
            System.exit(0);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void LoginbankerpanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginbankerpanelMouseEntered
        Loginbankerpanel.setBackground(new java.awt.Color(16, 69, 105));
    }//GEN-LAST:event_LoginbankerpanelMouseEntered

    private void LoginbankerpanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginbankerpanelMouseExited
        Loginbankerpanel.setBackground(new java.awt.Color(21,103,153));
    }//GEN-LAST:event_LoginbankerpanelMouseExited

    private void Loginbankerpanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Loginbankerpanel1MouseEntered
        Loginbankerpanel1.setBackground(new java.awt.Color(16, 69, 105));    }//GEN-LAST:event_Loginbankerpanel1MouseEntered

    private void Loginbankerpanel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Loginbankerpanel1MouseExited
        Loginbankerpanel1.setBackground(new java.awt.Color(21,103,153));
    }//GEN-LAST:event_Loginbankerpanel1MouseExited

    private void Loginbankerpanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Loginbankerpanel1MouseClicked
        LoginBanker lb=new LoginBanker();
        lb.setVisible(true);
        dispose();
    }//GEN-LAST:event_Loginbankerpanel1MouseClicked

    private void LoginbankerpanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginbankerpanelMouseClicked
        Login lg=new Login();
        lg.setVisible(true);
        dispose();
    }//GEN-LAST:event_LoginbankerpanelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Loginbankerpanel;
    private javax.swing.JPanel Loginbankerpanel1;
    private javax.swing.JPanel backgroundcolor;
    private javax.swing.JLabel banklogo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel option;
    private javax.swing.JLabel title1;
    private javax.swing.JLabel title2;
    // End of variables declaration//GEN-END:variables
}
