/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bms;

    

import java.awt.Color;
import java.sql.*;
/**
 *
 * @author KAMIL RAZA
 */
public class Profile extends javax.swing.JFrame {
    public static String mymail;
    
    /**
     * Creates new form Home
     */
    public Profile() {
        initComponents();
        
        try {
            Statement st=SplashScreen.db.conn.createStatement();
            ResultSet rs=st.executeQuery("SELECT * from information");
            
            while(rs. next()){
                if(rs.getString(13).equals(Login.uname)){
            
            namelabel.setText(rs.getString(1));
            acctypelabel.setText(rs.getString(5)); 
            addresslabel.setText(rs.getString(8));
            acclabel.setText(rs.getString(7));
            addresslabel.setText(rs.getString(12)); 
            maillabel.setText(rs.getString(2));
            mymail=maillabel.getText();
                }
            }
        } catch (SQLException ex) {
                ex.printStackTrace();        }
        
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel22 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        namelabel = new javax.swing.JLabel();
        acctypelabel = new javax.swing.JLabel();
        maillabel = new javax.swing.JLabel();
        addresslabel = new javax.swing.JLabel();
        acclabel = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        HomePanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TransferPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        AccountPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        CardsPanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ProfilePanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        LogoutPanel = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/icons8-close-window-30.png"))); // NOI18N
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 0, -1, -1));

        jPanel1.setBackground(new java.awt.Color(21, 103, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 152, 390, 10));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Address :");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, -1, -1));

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Account Number :");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, -1, 20));

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Account Type :");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, -1, -1));

        namelabel.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        namelabel.setForeground(new java.awt.Color(255, 255, 255));
        namelabel.setText("Username");
        jPanel3.add(namelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 280, 20));

        acctypelabel.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        acctypelabel.setForeground(new java.awt.Color(255, 255, 255));
        acctypelabel.setText("Type");
        jPanel3.add(acctypelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 210, 20));

        maillabel.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        maillabel.setForeground(new java.awt.Color(255, 255, 255));
        maillabel.setText("@gmail.com");
        jPanel3.add(maillabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 390, 20));

        addresslabel.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        addresslabel.setForeground(new java.awt.Color(255, 255, 255));
        addresslabel.setText("Address");
        jPanel3.add(addresslabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 370, 20));

        acclabel.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        acclabel.setForeground(new java.awt.Color(255, 255, 255));
        acclabel.setText("Account #");
        jPanel3.add(acclabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 210, 20));

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Account Holder Name :");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, -1, -1));

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Email :");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/maleicon.png"))); // NOI18N
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/gradient (7).png"))); // NOI18N
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 560));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 580, 560));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 41, 930, 600));

        HomePanel.setBackground(new java.awt.Color(21, 103, 153));
        HomePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomePanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HomePanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HomePanelMouseExited(evt);
            }
        });
        HomePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Home");
        HomePanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 70, -1));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/icons8-home-30.png"))); // NOI18N
        HomePanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 14, 70, -1));

        jPanel1.add(HomePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 90, 80));

        TransferPanel.setBackground(new java.awt.Color(21, 103, 153));
        TransferPanel.setPreferredSize(new java.awt.Dimension(90, 80));
        TransferPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TransferPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TransferPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TransferPanelMouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Transfer");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/icons8-data-transfer-30 (2).png"))); // NOI18N

        javax.swing.GroupLayout TransferPanelLayout = new javax.swing.GroupLayout(TransferPanel);
        TransferPanel.setLayout(TransferPanelLayout);
        TransferPanelLayout.setHorizontalGroup(
            TransferPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TransferPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TransferPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TransferPanelLayout.setVerticalGroup(
            TransferPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TransferPanelLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jPanel1.add(TransferPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 90, 80));

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("My Profile");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 930, 40));

        AccountPanel.setBackground(new java.awt.Color(21, 103, 153));
        AccountPanel.setPreferredSize(new java.awt.Dimension(90, 80));
        AccountPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AccountPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AccountPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AccountPanelMouseExited(evt);
            }
        });
        AccountPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Account");
        AccountPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 80, -1));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/icons8-money-bag-rupee-30 (2).png"))); // NOI18N
        AccountPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 14, 70, -1));

        jPanel1.add(AccountPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 90, 80));

        CardsPanel.setBackground(new java.awt.Color(21, 103, 153));
        CardsPanel.setPreferredSize(new java.awt.Dimension(90, 80));
        CardsPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CardsPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CardsPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CardsPanelMouseExited(evt);
            }
        });
        CardsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Cards");
        CardsPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 90, -1));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/icons8-mastercard-credit-card-30.png"))); // NOI18N
        CardsPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 14, 70, -1));

        jPanel1.add(CardsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 90, 80));

        ProfilePanel.setBackground(new java.awt.Color(21, 103, 153));
        ProfilePanel.setPreferredSize(new java.awt.Dimension(90, 80));
        ProfilePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ProfilePanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ProfilePanelMouseExited(evt);
            }
        });
        ProfilePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Profile");
        ProfilePanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 90, -1));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/icons8-male-user-30.png"))); // NOI18N
        ProfilePanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 14, 70, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/icons8-arrow-30.png"))); // NOI18N
        ProfilePanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 30, -1));

        jPanel1.add(ProfilePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 90, 80));

        LogoutPanel.setBackground(new java.awt.Color(21, 103, 153));
        LogoutPanel.setPreferredSize(new java.awt.Dimension(90, 80));
        LogoutPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LogoutPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LogoutPanelMouseExited(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Logout");

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/icons8-logout-rounded-left-30.png"))); // NOI18N

        javax.swing.GroupLayout LogoutPanelLayout = new javax.swing.GroupLayout(LogoutPanel);
        LogoutPanel.setLayout(LogoutPanelLayout);
        LogoutPanelLayout.setHorizontalGroup(
            LogoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LogoutPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        LogoutPanelLayout.setVerticalGroup(
            LogoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LogoutPanelLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addContainerGap())
        );

        jPanel1.add(LogoutPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 90, 80));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomePanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomePanelMouseEntered
        HomePanel.setBackground(new java.awt.Color(16, 69, 105));
    }//GEN-LAST:event_HomePanelMouseEntered

    private void HomePanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomePanelMouseExited
        HomePanel.setBackground(new java.awt.Color(21,103,153));
    }//GEN-LAST:event_HomePanelMouseExited

    private void TransferPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TransferPanelMouseEntered
        TransferPanel.setBackground(new java.awt.Color(16, 69, 105));
    }//GEN-LAST:event_TransferPanelMouseEntered

    private void TransferPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TransferPanelMouseExited
        TransferPanel.setBackground(new java.awt.Color(21,103,153));
    }//GEN-LAST:event_TransferPanelMouseExited

    private void AccountPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccountPanelMouseEntered
        AccountPanel.setBackground(new java.awt.Color(16, 69, 105));
    }//GEN-LAST:event_AccountPanelMouseEntered

    private void AccountPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccountPanelMouseExited
        AccountPanel.setBackground(new java.awt.Color(21,103,153));
    }//GEN-LAST:event_AccountPanelMouseExited

    private void CardsPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CardsPanelMouseEntered
        CardsPanel.setBackground(new java.awt.Color(16, 69, 105));
    }//GEN-LAST:event_CardsPanelMouseEntered

    private void CardsPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CardsPanelMouseExited
        CardsPanel.setBackground(new java.awt.Color(21,103,153));
    }//GEN-LAST:event_CardsPanelMouseExited

    private void ProfilePanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProfilePanelMouseEntered
        ProfilePanel.setBackground(new java.awt.Color(16, 69, 105));
    }//GEN-LAST:event_ProfilePanelMouseEntered

    private void ProfilePanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProfilePanelMouseExited
        ProfilePanel.setBackground(new java.awt.Color(21,103,153));
    }//GEN-LAST:event_ProfilePanelMouseExited

    private void LogoutPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutPanelMouseEntered
        LogoutPanel.setBackground(new java.awt.Color(16, 69, 105));
    }//GEN-LAST:event_LogoutPanelMouseEntered

    private void LogoutPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutPanelMouseExited
        LogoutPanel.setBackground(new java.awt.Color(21,103,153));
    }//GEN-LAST:event_LogoutPanelMouseExited

    private void LogoutPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutPanelMouseClicked
        Login lg = new Login();
        lg.setVisible(true);
        dispose();
    }//GEN-LAST:event_LogoutPanelMouseClicked

    private void TransferPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TransferPanelMouseClicked
        Transfer tf=new Transfer();
        tf.setVisible(true);
        dispose();
    }//GEN-LAST:event_TransferPanelMouseClicked

    private void HomePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomePanelMouseClicked
Home h=new Home();
        h.setVisible(true);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_HomePanelMouseClicked

    private void CardsPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CardsPanelMouseClicked
        Cards c=new Cards();
        c.setVisible(true);
        dispose();
    }//GEN-LAST:event_CardsPanelMouseClicked

    private void AccountPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccountPanelMouseClicked
        Account ac=new Account();
        ac.setVisible(true);
        dispose();
    }//GEN-LAST:event_AccountPanelMouseClicked

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel22MouseClicked
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AccountPanel;
    private javax.swing.JPanel CardsPanel;
    private javax.swing.JPanel HomePanel;
    private javax.swing.JPanel LogoutPanel;
    private javax.swing.JPanel ProfilePanel;
    private javax.swing.JPanel TransferPanel;
    private javax.swing.JLabel acclabel;
    private javax.swing.JLabel acctypelabel;
    private javax.swing.JLabel addresslabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel maillabel;
    private javax.swing.JLabel namelabel;
    // End of variables declaration//GEN-END:variables
}
