package bms;




/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Umar Aziz
 */
public class SplashScreen extends javax.swing.JFrame {
    public static DB db = new DB();
    /**
     * Creates new form SplashScreen
     */
    public SplashScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        background = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Percentage = new javax.swing.JLabel();
        ProgressBar = new javax.swing.JProgressBar();
        BarText = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/small logo.png"))); // NOI18N
        background.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 800, -1));

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Copyright © 2020-2022 DBMS");
        background.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 800, -1));

        Percentage.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        Percentage.setForeground(new java.awt.Color(255, 255, 255));
        background.add(Percentage, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 420, -1, -1));

        ProgressBar.setForeground(new java.awt.Color(255, 255, 255));
        background.add(ProgressBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 800, -1));

        BarText.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        BarText.setForeground(new java.awt.Color(255, 255, 255));
        background.add(BarText, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, -1, -1));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DIGITAL BANK MANAGEMENT SYSTEM");
        background.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 790, 80));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/background.png"))); // NOI18N
        background.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
               // new SplashScreen().setVisible(true);
                
        SplashScreen LoadingWindow = new SplashScreen();
        LoadingWindow.setVisible(true);
        
                try{
        for(int i=0; i<=100; i++){
                Thread.sleep(40);
                LoadingWindow.Percentage.setText(i+"%");
                if(i==10){
                    LoadingWindow.BarText.setText("Turning On Modules...");
                }
                if(i==20){
                    LoadingWindow.BarText.setText("Loading Modules...");
                }
                if(i==20){
                    Thread.sleep(1000);
                }
                if(i==50){
                    LoadingWindow.BarText.setText("Connecting to Database...");
                }
                if(i==70){
                    LoadingWindow.BarText.setText("Connection Successful...");
                }
                if(i==90){
                    LoadingWindow.BarText.setText("Launching Application...");
                }
                if(i==95){
                    Thread.sleep(1000);
                }
                if(i==98){
                    LoadingWindow.BarText.setText("All Done!");
                }
                LoadingWindow.ProgressBar.setValue(i);    
            }
        }catch(Exception e){
            System.out.println(e);
        }
                LoadingWindow.setVisible(false);
                Main main=new Main();
                main.setVisible(true);
            
            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BarText;
    private javax.swing.JLabel Percentage;
    private javax.swing.JProgressBar ProgressBar;
    private javax.swing.JPanel background;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}
